// For You
export const GET_ALL_TOONS_PENDING = 'GET_ALL_TOONS_PENDING';
export const GET_ALL_TOONS_FULFILLED = 'GET_ALL_TOONS_FULFILLED';
export const GET_ALL_TOONS_REJECTED = 'GET_ALL_TOONS_REJECTED';

// Favorite
export const GET_ALL_FAVORITES_PENDING = 'GET_ALL_FAVORITES_PENDING';
export const GET_ALL_FAVORITES_FULFILLED = 'GET_ALL_FAVORITES_FULFILLED';
export const GET_ALL_FAVORITES_REJECTED = 'GET_ALL_FAVORITES_REJECTED';
